name: Java Continuous Integration with Gradle

on:
  push:
    branches:
      - 'issue/*'
      - 'feature/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-database.yml
        run: |
          cd ./src/main/resources

          touch ./application-database.yml

          echo "${{ secrets.DATABASE }}" >> ./application-database.yml

        shell: bash

      - name: make test application-database.yml
        run: |
          cd ./src/test/resources

          touch ./application-database.yml

          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build
